import { editor } from 'monaco-editor';

export const monokaiLight: editor.IStandaloneThemeData = {
  base: 'vs',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '75715E', fontStyle: 'italic' },
    { token: 'string', foreground: 'E6DB74' },
    { token: 'keyword', foreground: 'F92672', fontStyle: 'bold' },
    { token: 'number', foreground: 'AE81FF' },
    { token: 'variable', foreground: '66D9EF' },
    { token: 'variable.predefined', foreground: 'A6E22E' },
    { token: 'constant', foreground: 'AE81FF' },
    { token: 'operator', foreground: 'F92672' },
    { token: 'function', foreground: 'A6E22E' },
    { token: 'function.buildin', foreground: 'FD971F' },
    { token: 'class', foreground: 'A6E22E', fontStyle: 'bold' },
    { token: 'type', foreground: '66D9EF', fontStyle: 'italic' },
    { token: 'predefined', foreground: '66D9EF', fontStyle: 'italic' },
    { token: 'tag', foreground: 'F92672' },
    { token: 'attribute.name', foreground: 'A6E22E' },
    { token: 'attribute.value', foreground: 'E6DB74' },
    { token: 'meta.property-name', foreground: 'F92672' },
    { token: 'meta.selector', foreground: 'F92672' },
    { token: 'meta.separator', foreground: 'F92672' },
    { token: 'meta.brace', foreground: 'F8F8F2' },
    { token: 'meta.delimiter', foreground: 'F8F8F2' },
    { token: 'meta.definition', foreground: 'F92672' },
    { token: 'meta.embedded', foreground: 'A6E22E' },
    { token: 'variable.parameter', foreground: 'FD971F' },
    { token: 'support.variable.property', foreground: 'FD971F' },
    { token: 'keyword.control', foreground: '66D9EF' },
    { token: 'string.regexp', foreground: 'E6DB74' },
    { token: 'string.escape', foreground: 'E6DB74' },
    { token: 'punctuation.definition.string', foreground: 'E6DB74' },
    { token: 'punctuation.definition.variable', foreground: 'FD971F' },
    { token: 'meta.separator.comma', foreground: 'F8F8F2' },
    { token: 'meta.brace.round', foreground: 'F8F8F2' },
    { token: 'meta.brace.square', foreground: 'F8F8F2' },
    { token: 'meta.brace.curly', foreground: 'F8F8F2' },
    { token: 'support.type.primitive', foreground: '66D9EF' },
    { token: 'support.function', foreground: 'FD971F' },
    { token: 'support.class', foreground: 'FD971F' },
    { token: 'support.type', foreground: 'FD971F' },
    { token: 'variable.parameter.function', foreground: 'FD971F' },
    { token: 'variable.other.readwrite', foreground: '66D9EF' },
    { token: 'entity.name.function', foreground: 'FD971F' },
    { token: 'entity.name.class', foreground: 'A6E22E' },
    { token: 'entity.name.type', foreground: '66D9EF' },
    { token: 'entity.other.attribute-name', foreground: 'F92672' },
    { token: 'variable.other', foreground: 'FD971F' },
    { token: 'meta.tag', foreground: 'F92672' },
    { token: 'meta.attribute', foreground: 'A6E22E' },
  ],
  colors: {
    'editor.foreground': '#272822',
    'editor.background': '#F8F8F2',
    'editorLineNumber.foreground': '#75715E',
    'editorLineNumber.background': '#F8F8F2',
    'editor.selectionBackground': '#B4D5FE',
    'editor.lineHighlightBackground': '#F2F2F2',
    'editorCursor.foreground': '#000000',
  },
};
